### PR TITLE
Only compute container metrics when component metrics are available

### PR DESCRIPTION
**Pull request by ghost**
When minimal mode is configured the component metrics won't be available
for computation in analytics. They are computed instead by the collector
itself.

### CODE REVIEW

**Comment by TheConnMan** [comment]
Couple formatting issues. You should be able to use the Metricly CLI (https://github.com/metricly/metricly-cli) to format the files automatically.

**Review by TheConnMan — APPROVED** [review]
Looks great!

**Comment by rclagett** [comment]
Could we test the config to make sure metrics are computed in both modes?

**Comment by ghost** [comment]
> Could we test the config to make sure metrics are computed in both modes?

@rclagett I've now tested with both modes, here is a screenshot. 
Screen Shot 2020-05-18 at 14 57 21

There are gaps in the 5 min rollups for the non-minimal mode when the cpu percent exceeded 100% on the container. We may want to tackle that also as I think depending on resource allocations containers can easily exceed 100%

**Review by rclagett — COMMENTED** [review]
Thanks @evanzeller-vi! 

The valid max is what’s preventing >100 values from getting computed: https://github.com/netuitive-community-packages/netuitive-packages-docker/blob/dev/analyticConfigurations/metric_meta-docker.container.json#L64

I’m good to remove it. 

One other thing, could you add an entry to the HISTORY file?

**Pull request merged**
